SPACESHIP_AWS_SHOW=false
SPACESHIP_GCLOUD_SHOW=false
SPACESHIP_RUBY_SYMBOL='◈ '
SPACESHIP_DOCKER_SYMBOL='♓︎'

SPACESHIP_DIR_COLOR=004

SPACESHIP_GIT_BRANCH_PREFIX=''
SPACESHIP_GIT_BRANCH_COLOR=009
SPACESHIP_GIT_STATUS_COLOR=003
SPACESHIP_GIT_STATUS_DELETED='✕'

SPACESHIP_CHAR_SYMBOL_ROOT='→'
SPACESHIP_CHAR_SYMBOL_SECONDARY='⇢'
SPACESHIP_CHAR_SYMBOL_SUFFIX=' '
SPACESHIP_CHAR_COLOR_SUCCESS=243

SPACESHIP_ASYNC_SYMBOL='⋯'
